### ISSUE TITLE
How to configure the embedded wildfly instance

### ISSUE THREAD

**Issue by axelberle** [MatousJobanek/examples#2]
Hi Matous,
I studied your example for the embedded wildfly, and I am wondering how it would be possible to configure the embedded wildfly instance. For my tests I would need to adapt the standalone.xml, like adding a datasource for example. But how can you do that in the embedded wildfly?

Regards,
Axel

**Comment by MatousJobanek** [comment]
Hi,
sorry for my late response. You can try using an annotation `@ServerSetup`. An example how it can be used is here:
https://github.com/wildfly/wildfly-arquillian/blob/master/container-managed/src/test/java/org/jboss/as/arquillian/container/managed/ServerSetupDeploymentTestCase.java
